export const TABLE_SIZE_PX = 28;

export const CHAIR_BORDER_PX = 1;
export const CHAIR_SIZE_PX = 20;

export const COLUMN_CNT = 32;
export const DEFAULT_ROW_CNT = 15;

export const TABLE_POPOVER_BODY_WIDTH_REM = 14;
export const CHAIR_POPOVER_BODY_WIDTH_REM = 13.6;
export const POPOVER_PADDING_REM = 0.8;

export const TABLE_POPOVER_WIDTH_REM =
  TABLE_POPOVER_BODY_WIDTH_REM + POPOVER_PADDING_REM * 2;
export const CHAIR_POPOVER_WIDTH_REM =
  CHAIR_POPOVER_BODY_WIDTH_REM + POPOVER_PADDING_REM * 2;
